############################################################################
# Clash with Dashboard
# https://central-x.com
############################################################################
name: Release Clash Images

on:
  workflow_dispatch:

jobs:
  #################################################################
  # Release Clash
  release:
    name: Release Clash Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker(QEMU)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker(Buildx)
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          platforms: linux/amd64,linux/arm64
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #============================ Build ============================
      - name: Release Images
        uses: docker/bake-action@v5
        with:
          targets: clash
          workdir: ./clash
          push: true
  #################################################################
  # Test Clash
  test:
    name: Test Clash Images
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #======================== Test OpenJDK =========================
      - name: Test Images
        run: docker run --rm centralx/clash:latest clash -v